### ISSUE TITLE
on-campus-counter readthedocs error

### ISSUE THREAD

**Issue by craigboman** [ezpaarse-project/ezpaarse-middlewares#11]
Currently the readthedocs middleware info for on-campus-counter links out to wikipedia when it should be linking internally to other documentation pages. https://ezpaarse.readthedocs.io/en/master/development/middlewares.html

**Comment by craigboman** [comment]
Please update the middleware docs above to point to at least the on-campus-counter github page.

**Comment by tporquet** [comment]
Hi Craig,
We are currently working on articulating and including the middlewares' documentation into the general documentation (which is also why we recently moved from readthedocs --> github.io pages). It should soon be easier to access the access the middleware doc.

**Comment by craigboman** [comment]
Yes. Enjoying the new docs site. Thanks guys. 👍
