### ISSUE TITLE
Additional URL Source of Ebscohost Database IDs

### ISSUE THREAD

**Issue by craigboman** [ezpaarse-project/ezpaarse-middlewares#17]
I'm not sure where to plug in this data so I'll start with an issue here. It is hypothetically possible to also extract database IDs from the "bdata=" Ebscohost url parameter. Have you looked at extracting or converting the longer hashed string IDs into database id's that can be used as part of the publisher knowledge base lookup? Reverse engineering this is really tough, since if end user has all of the Ebschost databases selected the bdata=.... will be a longer list of hashed string database IDs. However the hashed database IDs are not a one to one ratio. So if end user has 30 EDS databases selected there may be 20 unique IDs in the bdata= string. I could hypothetically create a pull request for the list.json attaching to the end of the list some of my bdata= IDs that I've been able to match to the actual database name. But from a programmatic standpoint, I don't think I should do that since list.json is probably mapped to the url parameter "db=", but could you code it to also look for "bdata=..." and the corresponding hashed database ID string? bdata=JmRiPWFzbiZ0eXBlPTAmc2VhcmNoTW9kZT1TdGFuZGFyZCZzaXRlPWVob3N0LWxpdmU for instance describes the a basic search of Academic Search Ultimate. bdata=JmRiPWFzbiZ0eXBlPTEmc2VhcmNoTW9kZT1TdGFuZGFyZCZzaXRlPWVob3N0LWxpdmU would be an advanced search (JmRiPWFzbiZ0eXBlPTE) of Academic Search Ultimate.

**Comment by nojhamster** [comment]
You're right, it seems that `bdata` is actually usable. I had a look at it, and it revealed to be a `base64` encoded querystring. The example you provide turns into this once decoded : `&db=asn&type=1&searchMode=Standard&site=ehost-live`. We could use it to populate `db_id`.

Actually, we already do something similar with the URL `hash` that can contain a querystring with `db` in it. However, I don't know how it looks when multiples databases are selected, but it's not an issue for URLs that aren't searches.

I'll be looking at the parser ASAP and will close this issue when it's done.

**Comment by craigboman** [comment]
Awesome! Hadn't thought about base64 decoding that. :) Nice job!

**Comment by nojhamster** [comment]
The parser can now populate `db_id` from `bdata`, cf https://github.com/ezpaarse-project/ezpaarse-platforms/commit/8d70f9491b71928283a649d6642f4bb754eef7e1
