### ISSUE TITLE
Middleware that analyzes user-agent

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/ezpaarse-middlewares#6]
Istex use case : possibility to fill the **SID** with data extracted from the user agent

**Comment by kerphi** [comment]
the first step could be to fill the sid only if it is empty

but for a more advanced step, it could be interesting, if the sid is already filled, to concatenate the simplified user-agent at the end of the sid ?
For example: if we have sid=istex-view in the url and the simplified user-agent is browser-chrome, then the sid will be sid=istex-view,browser-chrome

but would it be possible to handle multivalued sid in kibana?

**Comment by nojhamster** [comment]
Don't know, but I guess a simple two-level pie chart could do the job if we just have a **sid** and another field with the simplified **user-agent**

**Comment by kerphi** [comment]
Ok good idea for a double field: sid & simplified user-agent (sua :p)

But I have still the question about the ability of kibana about handling multi-valued fields because I have the idea to concatenate sid values ad the istex-view side. Here is a use case:
1) user comes from google scholar,
2) it will then be redirected to istex-view,  so its sid is sid=google
3) it will then be redirected (or AJAX request) to PDF on the API side, so I would like to populate sid=istex-view,google so that it's possible to know the user is coming from google

**Comment by kerphi** [comment]
Je reviens à la charge pour le "découpage" des multi-sid.
Ca serait jouable dans le kibana de gérer un tableau pour la valeur du sid dans chaque EC ?

Un peu à la manière de l'attribut "location" (mais avec un tableau) cf :

![image](https://cloud.githubusercontent.com/assets/328244/26627765/d0f68da8-45fb-11e7-9b12-ae9e9c130fec.png)

**Comment by nojhamster** [comment]
I don't know how it behaves when aggregating, but Kibana can deal with array data. Investigation needed.

**Comment by nojhamster** [comment]
[UA-parser](http://faisalman.github.io/ua-parser-js/) looks like a good starting point. Currently looking for alternatives.

**Comment by kerphi** [comment]
Not sure it will cover command line tools. It seams to cover browsers

Le mar. 6 juin 2017 14:18, Yannick Schurter <notifications@github.com> a
écrit :

**Comment by nojhamster** [comment]
Yep, most of (all?) UA-parsers just support real browsers. We'll have to take care of CLI tools by ourself, however it should spare us the hard work of struggling in the UA-String jungle.

**Comment by nojhamster** [comment]
[useragent](https://github.com/3rd-Eden/useragent) seems to be a more viable alternative for parsing the most common UA strings. A benchmark against [UA-parser](http://faisalman.github.io/ua-parser-js/) shows it performs 9 times faster. Considering the heavy task of parsing the UA-String (ie. applying a wide range of RegExps to the UA string), useragent should have a weaker impact on the overall performances. I'm going to try it out.
